apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp2-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp2-web
  template:
    metadata:
      labels:
        app: cp2-web
    spec:
      imagePullSecrets:
        - name: acr-credentials
      containers:
        - name: nginx
          image: acrmerliarizacp2.azurecr.io/web-k8s:casopractico2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-storage
              mountPath: /usr/share/nginx/html/data
      volumes:
        - name: html-storage
          persistentVolumeClaim:
            claimName: cp2-storage
